//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtonWebApi.Infrastructure.Repositories.Scripts.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AtonWebApi.Infrastructure.Repositories.Scripts.Account.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Users (
        ///    Guid, Login, Password, Name, Gender, Birthday,
        ///    Admin, CreatedOn, CreatedBy
        ///) VALUES ( @Guid, @Login, @Password, @Name, @Gender, @Birthday, @Admin, @CreatedOn, @CreatedBy);.
        /// </summary>
        internal static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Users WHERE Guid = @Guid;.
        /// </summary>
        internal static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Users WHERE RevokedOn IS NULL;.
        /// </summary>
        internal static string GetActiveUsers {
            get {
                return ResourceManager.GetString("GetActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Users WHERE Login = @Login;.
        /// </summary>
        internal static string GetUserByLogin {
            get {
                return ResourceManager.GetString("GetUserByLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Users
        ///WHERE RevokedOn IS NULL
        ///  AND Birthday IS NOT NULL
        ///  AND AGE(CURRENT_DATE, Birthday) &gt; @Age * INTERVAL &apos;1 year&apos;;.
        /// </summary>
        internal static string GetUsersOlderThan {
            get {
                return ResourceManager.GetString("GetUsersOlderThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS Users (
        ///                                     Guid UUID PRIMARY KEY,
        ///                                     Login VARCHAR(50) UNIQUE NOT NULL CHECK (Login ~ &apos;^[a-zA-Z0-9]+$&apos;),
        ///    Password VARCHAR(100) NOT NULL CHECK (Password ~ &apos;^[a-zA-Z0-9$./]+$&apos;),
        ///    Name VARCHAR(100) NOT NULL CHECK (Name ~ &apos;^[a-zA-Zа-яА-ЯёЁ ]+$&apos;),
        ///    Gender INT NOT NULL CHECK (Gender BETWEEN 0 AND 2),
        ///    Birthday DATE,
        ///    Admin BOOLEAN NOT NULL,
        ///    CreatedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitializeDatabase {
            get {
                return ResourceManager.GetString("InitializeDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users SET
        ///                 Login = @Login,
        ///                 Password = @Password,
        ///                 Name = @Name,
        ///                 Gender = @Gender,
        ///                 Birthday = @Birthday,
        ///                 Admin = @Admin,
        ///                 ModifiedOn = @ModifiedOn,
        ///                 ModifiedBy = @ModifiedBy,
        ///                 RevokedOn = @RevokedOn,
        ///                 RevokedBy = @RevokedBy
        ///WHERE Guid = @Guid;.
        /// </summary>
        internal static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
    }
}
